config/routes.rb
Rails.application.routes.draw do



  devise_for :users
  resources :logs
  resources :step_statuses

  get 'landing/new'
  get 'landing/create'

  get 'changes/project_autocomplete', to: 'changes#project_autocomplete', as: 'changes_project_autocomplete'
  get 'changes/owner_autocomplete', to: 'changes#owner_autocomplete', as: 'changes_owner_autocomplete'
  resources :projects

  resources :staffs
  resources :steps,   :except => [:index, :new]
  resources :changes
  root to: 'landing#index'

  get 'steps/new/:change_id', to: 'steps#new', as: 'new_step'
  post 'steps/:id/log', to: 'steps#upload', as: 'steps_log_upload'
  get 'steps/:id/download/:log', to: 'steps#download', as: 'steps_download'


#  get 'steps/edit/:id', to: 'steps#edit', as: 'edit_step'
#  get 'steps/', to: 'steps#new', as: 'steps'
#  get 'steps/:id', to: 'steps#show', as: 'show_step'

#  post 'steps/', to: 'steps#create'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/staff.rb
class Staff < ApplicationRecord

  has_many :steps, through: :changeRequests
  has_many :changeRequests, class_name: 'Change', foreign_key: 'owner_id'


  has_many :project_members
  has_many :projects, through: :project_members

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :email, :contact)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(staff) do |f| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :contact %>
    <%= f.text_field :contact %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table>
  <thead class="table table-hover table-responsive">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.email %></td>
        <td><%= staff.contact %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @staff.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @staff.contact %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>