config/routes.rb
Rails.application.routes.draw do



  devise_for :users
  resources :logs
  resources :step_statuses

  get 'landing/new'
  get 'landing/create'

  get 'changes/project_autocomplete', to: 'changes#project_autocomplete', as: 'changes_project_autocomplete'
  get 'changes/owner_autocomplete', to: 'changes#owner_autocomplete', as: 'changes_owner_autocomplete'
  resources :projects

  resources :staffs
  resources :steps,   :except => [:index, :new]
  resources :changes
  root to: 'landing#index'

  get 'steps/new/:change_id', to: 'steps#new', as: 'new_step'
  post 'steps/:id/log', to: 'steps#upload', as: 'steps_log_upload'
  get 'steps/:id/download/:log', to: 'steps#download', as: 'steps_download'


#  get 'steps/edit/:id', to: 'steps#edit', as: 'edit_step'
#  get 'steps/', to: 'steps#new', as: 'steps'
#  get 'steps/:id', to: 'steps#show', as: 'show_step'

#  post 'steps/', to: 'steps#create'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/change.rb
class Change < ApplicationRecord

  has_many :steps

  belongs_to :project
  accepts_nested_attributes_for :project

  belongs_to :owner, :class_name => 'User'
  accepts_nested_attributes_for :owner

  attr_accessor :links_to_display

end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController
  before_action :set_change, only: [:show, :edit, :update, :destroy]
  #before_action :process_owner, only: [:create]

  autocomplete :project, :name, :full => true

  # GET /changes
  # GET /changes.json
  def index
    @changes = Change.all
  end

  # GET /changes/1
  # GET /changes/1.json
  def show
    @steps = @change.steps.reorder('stepNo ASC').includes(:assignedTo)
    @step = Step.new
    @step.id = (Step.last.id) +1
    @colors = StepStatus.all

    @change.links_to_display = %i(more_info add_step_modal edit_change_to clone_change_to update_change_status)

  end

  # GET /changes/new
  def new

    @change = Change.new
    @change.links_to_display = %i(clone_change_from)
  end

  # GET /changes/1/edit
  def edit

    @change.links_to_display = %i(more_info add_step_modal edit_change_to clone_change_to update_change_status)
  end

  # POST /changes
  # POST /changes.json
  def create
    @change = Change.new(change_params)
    @change.owner = process_owner
    @change.project = process_project
    @change.links_to_display = %i(clone_change_from)


    respond_to do |format|
      if @change.save
        format.html { redirect_to @change, notice: 'Change was successfully created.' }
        format.json { render :show, status: :created, location: @change }
      else
        format.html { render :new }
        format.json { render json: @change.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /changes/1
  # PATCH/PUT /changes/1.json
  def update
    respond_to do |format|
      if @change.update(change_params)
        format.html { redirect_to @change, notice: 'Change was successfully updated.' }
        format.json { render :show, status: :ok, location: @change }
      else
        format.html { render :edit }
        format.json { render json: @change.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /changes/1
  # DELETE /changes/1.json
  def destroy
    @change.destroy

    recount_steps


    respond_to do |format|
      format.html { redirect_to changes_url, notice: 'Change was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def project_autocomplete
    @projects = Project.order(:name).where("name LIKE ?", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json {
        render json: @projects.map(&:name).to_json
      }
    end
  end

  def owner_autocomplete
    @users = User.order(:name).where("name LIKE ?", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json {
        render json: @users.map(&:name).to_json
      }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_change
    @change = Change.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def change_params
    params.require(:change).permit(:name, :description, :implementation_date, :owner, :project)
  end

  def process_owner
    @change.owner = User.find_by_name(params[:change][:owner_attributes][:name]) #unless @change.owner.id == params[:change][:owner_attributes][:id].to_i
  end

  def process_project
    @change.project = Project.find_by_name(params[:change][:project_attributes][:name]) #unless @change.owner.id == params[:change][:owner_attributes][:id].to_i
  end


end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/views/changes/_form.html.erb
<div class="container">

  <br/>

  <% present change do |change_presenter| %>
      <%= bootstrap_form_for(change) do |f| %>

          <div class="row">
            <div class="col-sm-6">
              <%= f.text_field :name, label: 'Change name' %>
            </div>
            <div class="col-sm-6">

              <%= f.fields_for :project_attributes, @change.project do |c| %>
                  <%= c.text_field :name, class: "search-query", type: "search", data: {autocomplete: changes_project_autocomplete_path}, 'data-auto-focus' => true, label: 'Project (NAME)' %>

              <% end %>


            </div>
          </div>

          <div class="row">
            <div class="col-sm-6">


              <%= f.fields_for :owner_attributes, @change.owner do |c| %>
                  <%#= c.number_field :id, label: 'Owner (ID):' %>
                  <%= c.text_field :name, class: "search-query", type: "search", data: {autocomplete: changes_owner_autocomplete_path}, 'data-auto-focus' => true, label: 'Change owner (NAME)' %>
              <% end %>


            </div>
            <div class="col-sm-6">

              <label>Implementation date:</label>

              <div class='input-group date' id='datetimepicker1'>
<span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>



                <%= f.datetime_local_field(:implementation_date, skip_label: true, id: 'input_datetimepicker1') %>


              </div>


              <script type="text/javascript">
                $(function () {
                  $('#datetimepicker1').datetimepicker({
                    format: 'LLLL',

                  });

                  $('#input_datetimepicker1').val("<%=  change_presenter.print_implementation_date %>");

                });
              </script>


            </div>
          </div>


          <%= f.text_area :description, label: 'Change Desription', rows: 10 %>
          <%= f.submit class: 'btn btn-success pull-right' %>

      <% end %>

      </div>
  <% end %>

app/views/changes/edit.html.erb
<%= render partial: 'landing/page_header', locals: {object: @change} %>

<% if @change.errors.any? %>
    <div class="error_explanation" style="margin-top: 0px;">
      <div class="container">
        <%= pluralize(@change.errors.count, "error") %> prohibited this project from being saved.
      </div>
    </div>
<% end %>

<%= render 'layouts/messages' %>

<%= render 'form', change: @change %>

app/views/changes/index.html.erb
<div class="container">


  <p id="notice"><%= notice %></p>

  <h1>Changes</h1>


  <table class="table table-hover table-responsive">
    <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Coordinator</th>
      <th>Owner</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @changes.each do |change| %>
        <tr>
          <td><%= change.name %></td>
          <td><%= change.description %></td>
          <td><%= change.coordinator.name %></td>
          <td><%= change.owner.name %></td>
          <td><%= link_to 'Show', change %></td>
          <td><%= link_to 'Edit', edit_change_path(change) %></td>
          <td><%= link_to 'Destroy', change, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Change', new_change_path %>
</div>

app/views/changes/new.html.erb
<%= render partial: 'landing/page_header', locals: {object: @change} %>

<%= render 'form', change: @change %>

app/views/changes/show.html.erb
<%= render partial: 'landing/page_header', locals: {object: @change} %>


<div class="container">


  <br/>

  <table class="table table-hover table-responsive">
    <thead>
    <tr>
      <th>#</th>
      <th>Action</th>
      <th>Status</th>
      <th>Log</th>
      <th>Assigned to</th>
    </tr>
    </thead>

    <tbody>
    <% @steps.each do |step| %>
        <tr>
          <td><strong><%= link_to step.stepNo, edit_step_path(step), remote: true %></strong></td>
          <td><%= link_to step.action, edit_step_path(step), remote: true %></td>
          <td><%= link_to step.status, edit_step_path(step), remote: true, class: "label label--#{step.status}" %> </td>
          <td><%= link_to "<span class='badge alert-info'>#{step.logs_count}</span>".html_safe, step %></td>
          <td><%= link_to step.assignedTo.name, '#' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

</div>

<div class="js-edit-modal"></div>