config/routes.rb
Rails.application.routes.draw do



  devise_for :users
  resources :logs
  resources :step_statuses

  get 'landing/new'
  get 'landing/create'

  get 'changes/project_autocomplete', to: 'changes#project_autocomplete', as: 'changes_project_autocomplete'
  get 'changes/owner_autocomplete', to: 'changes#owner_autocomplete', as: 'changes_owner_autocomplete'
  resources :projects

  resources :staffs
  resources :steps,   :except => [:index, :new]
  resources :changes
  root to: 'landing#index'

  get 'steps/new/:change_id', to: 'steps#new', as: 'new_step'
  post 'steps/:id/log', to: 'steps#upload', as: 'steps_log_upload'
  get 'steps/:id/download/:log', to: 'steps#download', as: 'steps_download'


#  get 'steps/edit/:id', to: 'steps#edit', as: 'edit_step'
#  get 'steps/', to: 'steps#new', as: 'steps'
#  get 'steps/:id', to: 'steps#show', as: 'show_step'

#  post 'steps/', to: 'steps#create'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/step_statuses_controller.rb
class StepStatusesController < ApplicationController
  before_action :set_step_status, only: [:show, :edit, :update, :destroy]

  # GET /step_statuses
  # GET /step_statuses.json
  def index
    @step_statuses = StepStatus.all
  end

  # GET /step_statuses/1
  # GET /step_statuses/1.json
  def show
  end

  # GET /step_statuses/new
  def new
    @step_status = StepStatus.new
  end

  # GET /step_statuses/1/edit
  def edit
  end

  # POST /step_statuses
  # POST /step_statuses.json
  def create
    @step_status = StepStatus.new(step_status_params)

    respond_to do |format|
      if @step_status.save
        format.html { redirect_to @step_status, notice: 'Step status was successfully created.' }
        format.json { render :show, status: :created, location: @step_status }
      else
        format.html { render :new }
        format.json { render json: @step_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /step_statuses/1
  # PATCH/PUT /step_statuses/1.json
  def update
    respond_to do |format|
      if @step_status.update(step_status_params)
        format.html { redirect_to @step_status, notice: 'Step status was successfully updated.' }
        format.json { render :show, status: :ok, location: @step_status }
      else
        format.html { render :edit }
        format.json { render json: @step_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /step_statuses/1
  # DELETE /step_statuses/1.json
  def destroy
    @step_status.destroy
    respond_to do |format|
      format.html { redirect_to step_statuses_url, notice: 'Step status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step_status
      @step_status = StepStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_status_params
      params.require(:step_status).permit(:name)
    end
end

app/helpers/step_statuses_helper.rb
module StepStatusesHelper
end

app/views/step_statuses/_form.html.erb
<%= form_for(step_status) do |f| %>
  <% if step_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(step_status.errors.count, "error") %> prohibited this step_status from being saved:</h2>

      <ul>
      <% step_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/step_statuses/edit.html.erb
<h1>Editing Step Status</h1>

<%= render 'form', step_status: @step_status %>

<%= link_to 'Show', @step_status %> |
<%= link_to 'Back', step_statuses_path %>

app/views/step_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Step Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @step_statuses.each do |step_status| %>
      <tr>
        <td><%= step_status.name %></td>
        <td><%= link_to 'Show', step_status %></td>
        <td><%= link_to 'Edit', edit_step_status_path(step_status) %></td>
        <td><%= link_to 'Destroy', step_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step Status', new_step_status_path %>

app/views/step_statuses/new.html.erb
<h1>New Step Status</h1>

<%= render 'form', step_status: @step_status %>

<%= link_to 'Back', step_statuses_path %>

app/views/step_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @step_status.name %>
</p>

<%= link_to 'Edit', edit_step_status_path(@step_status) %> |
<%= link_to 'Back', step_statuses_path %>