config/routes.rb
Rails.application.routes.draw do



  devise_for :users
  resources :logs
  resources :step_statuses

  get 'landing/new'
  get 'landing/create'

  get 'changes/project_autocomplete', to: 'changes#project_autocomplete', as: 'changes_project_autocomplete'
  get 'changes/owner_autocomplete', to: 'changes#owner_autocomplete', as: 'changes_owner_autocomplete'
  resources :projects

  resources :staffs
  resources :steps,   :except => [:index, :new]
  resources :changes
  root to: 'landing#index'

  get 'steps/new/:change_id', to: 'steps#new', as: 'new_step'
  post 'steps/:id/log', to: 'steps#upload', as: 'steps_log_upload'
  get 'steps/:id/download/:log', to: 'steps#download', as: 'steps_download'


#  get 'steps/edit/:id', to: 'steps#edit', as: 'edit_step'
#  get 'steps/', to: 'steps#new', as: 'steps'
#  get 'steps/:id', to: 'steps#show', as: 'show_step'

#  post 'steps/', to: 'steps#create'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/step.rb
class Step < ApplicationRecord

  belongs_to :change

  belongs_to :assignedTo, :class_name => 'User', :foreign_key => 'assignedTo'
  accepts_nested_attributes_for :assignedTo

  has_many :logs

  validates :change_id, presence: true

  attr_accessor :links_to_display



end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  #before_action :process_assignedTo, only: [:update]
  before_action :set_step, only: [:show, :edit, :update, :destroy, :upload]
 # before_action :set_change, only: [:create] # new crash to create new step



  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step.links_to_display = %i(more_info add_log edit_step)
  end

  def upload

    # general folder to store files
    storage_folder = 'storage/'
    # organization folders
    storage_hier = Time.now.strftime("%Y/%m/")

    FileUtils::mkdir_p (storage_folder + storage_hier)

    log = Log.new(step: @step)

    unless params[:upload][:file].nil?

      final_file_name = Log.last.id.to_s + '_' + params[:upload][:file].original_filename
      log.file_name = final_file_name
      log.log_path = storage_folder + storage_hier


      final_file_name = storage_folder + storage_hier + final_file_name
      FileUtils.mv(params[:upload][:file].tempfile.path, final_file_name)

      require 'rack/mime'
      log.mime_type = MIME::Types.type_for(final_file_name).first.content_type
      @step.logs << log

    end

    if !params[:upload][:text_field_log].empty?


      file = Tempfile.new('text_field_log')
      file.write(params[:upload][:text_field_log])
      file.close

      log.log_path  = storage_folder + storage_hier
      final_file_name = Log.last.id.to_s + '_text_field_log.txt'

      log.file_name = final_file_name
      FileUtils.mv(file.path, log.log_path + final_file_name)

     # require 'rack/mime'
      log.mime_type = MIME::Types.type_for(final_file_name).first.content_type

      @step.logs << log
    end

    flash[:notice] = 'Log was successfully created.'
    render :show


  end

  def download

    log = Log.find(params[:log])


    send_file(
        log.log_path + log.file_name,
        filename: log.file_name
    )

  end

  # GET /steps/new
  def new
    @step = Step.new
    @step.id = (Step.last.id) + 1

    @step.change_id = params[:change_id]
    @step.links_to_display = %i(empty)

    @change = Change.find(params[:change_id])
    @step.stepNo = @change.steps.count + 1

    @step.assignedTo = Staff.first

    @step_statuses = StepStatus.all

#    @step.save


    render 'edit.js.erb'


  end

  # GET /steps/1/edit
  def edit


    @step_statuses = StepStatus.all

    respond_to do |format|
      format.js
    end

  end


  # POST /steps
  # POST /steps.json
  def create

    @step = Step.new(step_params)
    @step.assignedTo = process_assignedTo

    @step.stepNo = @step.change.steps.count +1

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step.change, notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update


    @step = Step.find_by_id(params[:id])

    @step.attributes = step_params
    @step.assignedTo = process_assignedTo


    respond_to do |format|

      if @step.save(validate: false)
        format.html { redirect_to @step.change, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { redirect_to @step.change, notice: @step.errors }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy

    recount_steps

    respond_to do |format|
      format.html { redirect_to @step.change, notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_step
    @step = Step.find(params[:id])
  end

  def set_change
  #  @step = Step.new(step_params)
    @step = Step.where(id: params[:id])

    @change = if @step.nil?
                Change.find(params[:change_id])
              else
                @step.change
              end
  end


  def recount_steps
    counter = 1

    @step.change.steps.each do |step|
      step.stepNo = counter
      step.save
      counter = counter +1
    end

  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def step_params
    #params.require(:step).permit(:stepNo, :action, :status, :log, :change_id)
    params.require(:step).permit(:stepNo, :action, :status, :log, :change_id, assignedTo_attributes: [:name])
  end

  def process_assignedTo

    #@step = set_step if @step.nil?

    @step.assignedTo = User.find_by_name(params[:step][:assignedTo_attributes][:name]) #unless @step.assignedTo.nil? ||  @step.assignedTo.id == params[:step][:assignedTo_attributes][:id].to_i
    @step.assignedTo

  end

end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/_form.html.erb
<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">

        <%= bootstrap_form_for(@step) do |f| %>
            <% if @step.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

                  <ul>
                    <% @step.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <%#= f.number_field :id %>
            <%= f.hidden_field :change_id %>


            <%= f.number_field :stepNo, label: 'Step #' %>

            <%= f.text_field :action, label: 'Action' %>


            <fieldset class="form-group">
              <hr/>
              <%= f.fields_for :assignedTo_attributes, @step.assignedTo do |c| %>
                  <%= c.text_field :name, class: "search-query", type: "search", data: {autocomplete: changes_owner_autocomplete_path}, 'data-auto-focus' => true, label: 'Assigned to' %>
              <% end %>
              <hr/>
            </fieldset>


            <label>Status:</label>
            <% @step_statuses.each do |st| %>

                <span class="step_label">
                  <label  style="background-color: <%= st.color %>;">
                    <%= f.radio_button :status, st.name, label: st.name %>
                  </label>
                </span>

            <% end %>

            <div class="modal-footer">
              <%= link_to 'Delete Step'.html_safe, @step, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
              <%= f.submit class: 'btn btn-success' %>
            </div>


        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/steps/edit.js.erb
$(".js-edit-modal").html('<%= j render 'form' %>');

$('#myModal').modal('toggle');

app/views/steps/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <h1>Steps</h1>

  <table class="table table-hover table-responsive">
    <thead>
    <tr>
      <th>Stepno</th>
      <th>Action</th>
      <th>Status</th>
      <th>Log</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @steps.each do |step| %>
        <tr>
          <td><%= step.stepNo %></td>
          <td><%= step.action %></td>
          <td> <spam class="label label-primary"> <%= step.status %> </spam></td>
          <td><%= step.log %></td>
          <td><%= link_to 'Show', step %></td>
          <td><%= link_to 'Edit', edit_step_path(step) %></td>
          <td><%= link_to 'Destroy', step, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Step', new_step_path %>
</div>

app/views/steps/new.html.erb
<%= render partial: 'landing/page_header', locals: {object: @step} %>

<%= render 'form', step: @step %>

app/views/steps/show.html.erb
<%= render partial: 'landing/page_header', locals: {object: @step} %>

<%= javascript_include_tag 'animations' %>

<div class="container">

  <br/>

  <%= bootstrap_form_for :upload, {:url => steps_log_upload_path, :html => {:multipart => true}} do |f| %>

      <div id="j--hide" class="panel panel-primary">
        <div class="panel-heading ">
          + New Log </h6>
        </div>

        <div class="panel-body">
          <div class="row">
            <div class="col-sm-10">
              <%= f.file_field('file', class: "btn btn-info", label: "Upload log file:") %>
            </div>
            <div class="col-sm-2">
              <%= submit_tag("Submit form", class: "btn btn-success pull-right") %>
            </div>
          </div>
          <br/>
          <%= f.text_area :text_field_log, style: "width: 100%;", rows: "7", label: "Paste your text log:" %>
        </div>

        <div class="panel-footer">
          <div class="row">
            <div class="col-sm-12">
              <%= submit_tag("Submit form", class: "btn btn-success pull-right") %>
              <%= button_tag "Reset form", type: :reset, class: "btn btn-danger" %>

            </div>
          </div>
        </div>
      </div>
  <% end %>


  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

    <% counter = 0 %>
    <% @step.logs.each do |log| %>

        <div class="panel panel-info">
          <div class="panel-heading" role="tab" id="<%= "h_#{log.id}" %>">
            <h4 class="panel-title">
              <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="<%= "#c_#{log.id}" %>" aria-expanded="false" aria-controls=<%= "c_#{log.id}" %>>
                <%= "Log# #{counter = counter +1}" %>
              </a>
            </h4>
          </div>
          <div id="<%= "c_#{log.id}" %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="<%= "h_#{log.id}" %>">

            <div class="panel-body">
              <%= link_to('<i class="glyphicon glyphicon-download-alt"></i> Download this log'.html_safe, steps_download_url(:log => log), class: 'download-link')  %>
              <% if log.mime_type == 'text/plain' %>
                  <pre>
<%= render :file => log.log_path + log.file_name %>
                  </pre>
              <% end %>
            </div>

          </div>
        </div>

    <% end %>

    <% if counter == 0 %>
        <hr/>
        <h3>No log for this step</h3>

    <% end %>

  </div>
</div>